[package]
name = "xtask"
version = "0.1.0"
edition = "2018"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.66"
flate2 = "1.0.24"
pulldown-cmark = "0.11.0"
semver = "1.0.14"
tar = "0.4.38"
xflags = "0.3.1"
xshell = "0.2.2"
